# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horserace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='horse_club',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='horse_picture',
            field=models.ImageField(blank=True, null=True, upload_to='horserace/static/img/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
