# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horserace', '0002_auto_20170110_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
