# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horserace', '0003_auto_20170110_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='horse_picture',
            field=models.ImageField(blank=True, null=True, upload_to='/horserace/static/img/', verbose_name='Picture'),
        ),
    ]
