# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horserace', '0009_auto_20170113_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='horse_name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='horse_owner',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
